apiVersion: v1
kind: Service
metadata:
  name: external-access
spec:
  type: NodePort
  selector:
    instance-type: coordinator
  ports:
    - protocol: TCP
      name: bolt
      port: {{ $.Values.memgraph.ports.boltPort }}
      targetPort: {{ $.Values.memgraph.ports.boltPort }}
