apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "memgraph.fullname" . }}-main
spec:
  serviceName: {{ include "memgraph.fullname" . }}-main
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "memgraph.fullname" . }}-main
  template:
    metadata:
      labels:
        app: {{ include "memgraph.fullname" . }}-main
    spec:
      containers:
      - name: memgraph-main
        image: "{{ .Values.memgraph.image.repository }}:{{ .Values.memgraph.image.tag }}"
        imagePullPolicy: "{{ .Values.memgraph.image.pullPolicy }}"
        args: {{ toYaml .Values.memgraph.main.memgraphConfig | nindent 12 }}
        ports:
        - name: bolt
          containerPort: 7687
