{{- $validDataServices := list "" "LoadBalancer" "NodePort" "IngressNginx" }}
{{- if not (has .Values.externalAccessConfig.dataInstance.serviceType $validDataServices) }}
  {{- fail "Invalid value for externalAccessConfig.dataInstance.serviceType. Use '', 'LoadBalancer', 'NodePort', or 'IngressNginx'." }}
{{- end }}

{{- if or (eq $.Values.externalAccessConfig.dataInstance.serviceType "IngressNginx") (eq $.Values.externalAccessConfig.dataInstance.serviceType "") }}
  {{- /* No external service rendered for IngressNginx or empty string */}}
{{- else }}
  {{- range .Values.data }}
---
apiVersion: v1
kind: Service
metadata:
  name: memgraph-data-{{ .id }}-external
  {{- with $.Values.externalAccessConfig.dataInstance.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if eq $.Values.externalAccessConfig.dataInstance.serviceType "NodePort" }}
  type: NodePort
  {{- else if eq $.Values.externalAccessConfig.dataInstance.serviceType "LoadBalancer" }}
  type: LoadBalancer
  {{- end }}
  selector:
    app: memgraph-data-{{ .id }}
  ports:
    - protocol: TCP
      name: tcp-bolt-port
      port: {{ $.Values.ports.boltPort }}
      targetPort: {{ $.Values.ports.boltPort }}
  {{- end }}
{{- end }}
