{{- $validDataServices := list "LoadBalancer" "NodePort" "IngressNginx" }}
{{- if not (has .Values.externalAccessConfig.dataInstance.serviceType $validDataServices) }}
{{- fail "Invalid environment value for externalAccessConfig.dataInstance.serviceType. Use 'LoadBalancer', 'NodePort' or 'IngressNginx'."}}
{{- end }}


{{ if eq $.Values.externalAccessConfig.dataInstance.serviceType "IngressNginx"}}
# Placeholder
{{ else }}
{{- range .Values.data }}
---
apiVersion: v1
kind: Service
metadata:
  name: memgraph-data-{{ .id }}-external
spec:
{{ if eq $.Values.externalAccessConfig.dataInstance.serviceType "NodePort"}}
  type: NodePort
{{ else }}
  type: LoadBalancer
{{ end }}
  selector:
    app: memgraph-data-{{ .id }}
  ports:
    - protocol: TCP
      name: tcp-bolt-port
      port: {{ $.Values.ports.boltPort }}
      targetPort: {{ $.Values.ports.boltPort }}
{{- end }}
{{ end }}
