repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    exclude: ^charts/memgraph/templates/
  - id: check-json
  - id: mixed-line-ending
  - id: check-merge-conflict
  - id: detect-private-key
