---
# Source: memgraph/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: memgraph
  labels:
    helm.sh/chart: memgraph-0.1.2
    app.kubernetes.io/name: memgraph
    app.kubernetes.io/instance: memgraph
    app.kubernetes.io/version: "2.17.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: memgraph/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: memgraph
  labels:
    helm.sh/chart: memgraph-0.1.2
    app.kubernetes.io/name: memgraph
    app.kubernetes.io/instance: memgraph
    app.kubernetes.io/version: "2.17.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 7687
      targetPort: 7687
      protocol: TCP
      name: memgraph
    - port: 7444
      protocol: TCP
      name: websocket
    - port: 9091
      protocol: TCP
      name: http
    
  selector:
    app.kubernetes.io/name: memgraph
    app.kubernetes.io/instance: memgraph
---
# Source: memgraph/templates/statefulset.yaml
# templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memgraph
  labels:
    helm.sh/chart: memgraph-0.1.2
    app.kubernetes.io/name: memgraph
    app.kubernetes.io/instance: memgraph
    app.kubernetes.io/version: "2.17.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  serviceName: memgraph
  selector:
    matchLabels:
      app.kubernetes.io/name: memgraph
      app.kubernetes.io/instance: memgraph
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        helm.sh/chart: memgraph-0.1.2
        app.kubernetes.io/name: memgraph
        app.kubernetes.io/instance: memgraph
        app.kubernetes.io/version: "2.17.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      terminationGracePeriodSeconds: 1800
      securityContext:
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: memgraph-lib-storage
          persistentVolumeClaim:
            claimName: memgraph-ams2
      containers:
        - name: memgraph
          image: "memgraph/memgraph-mage:2.17.0"
          args:
          - "--also-log-to-stderr=true"
          - "--log-file=''"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          ports:
            - name: memgraph
              containerPort: 7687
            - name: websocket
              containerPort: 7444
            - name: http
              containerPort: 9091
          startupProbe:
            tcpSocket:
              port: memgraph
            failureThreshold: 240
            periodSeconds: 30  
          livenessProbe:
            tcpSocket:
              port: memgraph
            periodSeconds: 30
            timeoutSeconds: 20
          readinessProbe:
            tcpSocket:
              port: memgraph
            periodSeconds: 30
          env:
            - name: MEMGRAPH_USER
              value: memgraph
            - name: MEMGRAPH_PASSWORD
              value: 
            - name: MEMGRAPH_ENTERPRISE_LICENSE
              value: 
            - name: MEMGRAPH_ORGANIZATION_NAME
              value: 
          volumeMounts:
            - name: memgraph-lib-storage
              mountPath: /var/lib/memgraph
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - sn15-ams2               
  volumeClaimTemplates:
  - metadata:
      name: memgraph-lib-storage
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 500Gi
---
# Source: memgraph/templates/tests/test-connection.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: "memgraph-memgraph-test"
  labels:
    helm.sh/chart: memgraph-0.1.2
    app.kubernetes.io/name: memgraph
    app.kubernetes.io/instance: memgraph
    app.kubernetes.io/version: "2.17.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  template:
    spec:
      containers:
      - name: memgraph-test
        image: memgraph/memgraph:2.17.0
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "RETURN 0;" | mgconsole --host memgraph --port 7687
      restartPolicy: Never
  backoffLimit: 4
