name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
- katarinasupe
- antejavor
body:
- type: markdown
  attributes:
    value: |
      ## Bug Report

      **Chart type:**
      _Specify the chart type you experienced issues with (Memgraph Standalone, Memgraph HA,  Memgraph LAB)_

      **Chart version:**
      _Specify the version of the chart you are running._

      **What happened?**
      _Describe the issue and what you expected to happen._

      **Environment:**
      _Specify the environment where the issue occurred and how it could be related to the bug._

      **Relevant log output:**
      _Please copy and paste any relevant log output from pods and containers._
