apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name | default "generic-storage-class" }}
provisioner: {{ .Values.storageClass.provisioner | default "kubernetes.io/no-provisioner" }}
parameters:
  type: {{ .Values.storageClass.storageType | default "" }}
  fsType: {{ .Values.storageClass.fsType | default "ext4" }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy | default "Retain" }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode | default "WaitForFirstConsumer" }}
