apiVersion: v1
kind: Service
metadata:
  name: {{ include "memgraph-mcp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "memgraph-mcp.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "memgraph-mcp.selectorLabels" . | nindent 4 }}
